export default [

    {id:1 , razaoSocial: 'da hora', endereco: 'Rua Rio Das Neves', bairro: 'Ibura', cidade: 'Recife',email: 'dahoralins@hotmail.com', likes: 34, especialidade: 'Mecânica', logo: 'https://i.pinimg.com/originals/54/27/90/542790397e99c703291753baa0700d57.jpg', latitude: -8.1134775, longitude: -34.9388377}, 
    {id:2 , razaoSocial: 'do manoel', endereco: 'Rua Rio Das Neves', bairro: 'Ibura', cidade: 'Recife',email: 'mateus@hotmail.com', likes: 134, especialidade: 'Elétrica', logo: 'https://s3-sa-east-1.amazonaws.com/projetos-artes/fullsize%2F2011%2F08%2F25%2F19%2FWDL-Logo-6650_18118_041040027_1552849433.jpg', latitude: 10, longitude: 20}, 
    {id:3 , razaoSocial: 'bateu concertou', endereco: 'Rua Rio Das Neves', bairro: 'Ibura', cidade: 'Recife',email: 'joao@hotmail.com', likes: 531, especialidade: 'Elétrica', logo: 'https://ae01.alicdn.com/kf/HTB1QxqpRVXXXXbsXXXXq6xXFXXX4/Servi-o-de-repara-o-de-Servi-o-Oficina-Auto-Logotipo-Do-Carro-Adesivo-de-Parede.jpg_640x640.jpg', latitude: 10, longitude: 20}, 
    {id:4 , razaoSocial: 'melhor preço', endereco: 'Rua Rio Das Neves', bairro: 'Ibura', cidade: 'Recife',email: 'raqyuel@hotmail.com', likes: 12, especialidade: 'funilaria', logo: 'http://www.leaodesign.com.br/images/portfolio/criacao-de-logotipos/3-single.png', latitude: 10, longitude: 20}, 
    {id:5 , razaoSocial: 'da comunidade', endereco: 'Rua Rio Das Neves', bairro: 'Ibura', cidade: 'Recife',email: 'melhor_preço@hotmail.com', likes: 537, especialidade: 'Mecânica', logo: 'https://storage.googleapis.com/aquitempe-212001.appspot.com/imagens/e23612c9-1700-4dbd-b209-b06154193ff4/oficina%20mecanica%20e%20eletrica%20logo.png', latitude: 10, longitude: 20}, 
    {id:6 , razaoSocial: 'motos e Carros', endereco: 'Rua Rio Das Neves', bairro: 'Ibura', cidade: 'Recife',email: 'ana@hotmail.com', likes: 76, especialidade: 'funilaria', logo: 'http://mecsm.com.br/wp-content/uploads/2018/03/logo-mec-mecanica-retina.png', latitude: 10, longitude: 20}, 
    {id:7 , razaoSocial: 'joao e neto', endereco: 'Rua Rio Das Neves', bairro: 'Ibura', cidade: 'Recife',email: 'barbosa@hotmail.com', likes: 41, especialidade: 'Elétrica', logo: 'https://s3-sa-east-1.amazonaws.com/projetos-artes/fullsize%2F2014%2F10%2F05%2F13%2FLogo-e-Papelaria-LV-118391_25301_044356510_289312155.jpg', latitude: 10, longitude: 20}, 
    {id:8 , razaoSocial: 'moura', endereco: 'Rua Rio Das Neves', bairro: 'Ibura', cidade: 'Recife',email: 'silva@hotmail.com', likes: 97, especialidade: 'Mecânica', logo: 'http://www.portaldosmecanicos.com.br/wp-content/uploads/2016/07/logo-redes-sociais.png', latitude: 10, longitude: 20}, 
    {id:9 , razaoSocial: 'casa do mercedes', endereco: 'Rua Rio Das Neves', bairro: 'Ibura', cidade: 'Recife',email: 'melo@hotmail.com', likes: 64, especialidade: 'Elétrica', logo: 'http://lucenamanutencaoautomotiva.com.br/wp-content/uploads/2018/10/logo-lucena.png', latitude: 10, longitude: 20}, 
    {id:10 , razaoSocial: 'importados merchan', endereco: 'Rua Rio Das Neves', bairro: 'Ibura', cidade: 'Recife',email: 'tragoso@hotmail.com', likes: 314, especialidade: 'Mecânica', logo: 'http://oficinamotorpoint.com.br/wp-content/uploads/2016/01/logo-motor-point-lapa.png', latitude: 10, longitude: 20}, 
    {id:11 , razaoSocial: 'carango', endereco: 'Rua Rio Das Neves', bairro: 'Ibura', cidade: 'Recife',email: 'popoca@hotmail.com', likes: 6473, especialidade: 'Mecânica', logo: 'http://euroscan.com.br/wp-content/uploads/2017/11/LOGO-SCAS.png', latitude: 10, longitude: 20}, 
    {id:12 , razaoSocial: 'carango do Marcos', endereco: 'Rua Rio Das Neves', bairro: 'Ibura', cidade: 'Recife',email: 'ame@hotmail.com', likes: 1234, especialidade: 'funilaria', logo: 'https://a2roficinaauto.pt/wp-content/uploads/2018/05/Logo-small-square-copy.jpg', latitude: 10, longitude: 20}, 
    {id:13 , razaoSocial: 'shell',endereco: 'Rua Rio Das Neves', bairro: 'Ibura', cidade: 'Recife', email: 'cosfasdfta@hotmail.com', likes: 564, especialidade: 'Elétrica', logo: 'https://scontent.frec3-1.fna.fbcdn.net/v/t1.0-9/37069252_1899896400068418_7837900116416528384_n.jpg?_nc_cat=110&_nc_ht=scontent.frec3-1.fna&oh=54f4aae7d9708bc75b89757bbee7e81c&oe=5D8980E0', latitude: 10, longitude: 20}, 
    {id:14 , razaoSocial: 'brasil', endereco: 'Rua Rio Das Neves', bairro: 'Ibura', cidade: 'Recife',email: 'gasdf@hotmail.com', likes: 76, especialidade: 'funilaria', logo: 'http://www.logotiposdeempresas.com.br/wp-content/uploads/2011/05/logomarca_renotech_oficina_renault.jpg', latitude: 10, longitude: 20}, 

]